# Start with the Python image
FROM python:3.12-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Set up your working directory
RUN mkdir -p /code
WORKDIR /code

# Copy requirements and install Python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN set -ex && pip install --upgrade pip && pip install -r /tmp/requirements.txt && rm -rf /root/.cache/

# Copy the application code
COPY . /code
